name: flutter_admin_dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Rich text
  flutter_quill: ^9.2.3

  # Link handling
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.6

  # Intl (ต้อง 0.20.x เท่านั้น)
  intl: ^0.20.2

  # State
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0

  # UI
  google_fonts: ^6.2.1

  # Utils
  http: ^1.6.0
  file_picker: ^8.1.2
  excel: ^4.0.2
  file_saver: ^0.2.13
  table_calendar: ^3.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf